---
dependencies:
  - role: puppet-task
    puppet_task_repo: git@github.com:wenxin-wang/puppet-tasks.git
    puppet_task_dir: /tmp/puppet-system
    puppet_apply_args: >
      --certname={{puppet_certname}} --environment={{puppet_environment}}
      environments/{{puppet_environment}}/site.pp
    tags:
      - puppet-system
