---
- hosts: all
  roles:
    - base
    - puppet-tasks
  handlers:
    - include: handlers/packages_Debian.yml
      when: ansible_os_family == 'Debian'
    - include: handlers/packages_RedHat.yml
      when: ansible_os_family == 'RedHat'