---
- hosts: all
  roles:
    - base
    - puppet-system
  handlers:
    - include: handlers/packages_Debian.yml
      when: ansible_os_family == 'Debian'
    - include: handlers/packages_RedHat.yml
      when: ansible_os_family == 'RedHat'

- hosts: phystack
  roles:
    - puppet-phystack
  handlers:
    - include: handlers/packages_Debian.yml
      when: ansible_os_family == 'Debian'
    - include: handlers/packages_RedHat.yml
      when: ansible_os_family == 'RedHat'