---
- hosts: all
  roles:
    - base
  handlers:
    - include: handlers/packages_Debian.yml
      when: ansible_os_family == 'Debian'
    - include: handlers/packages_RedHat.yml
      when: ansible_os_family == 'RedHat'

- hosts:
    - main
    - server
  roles:
    - puppet-agent
    - librarian-puppet
    - hiera-eyaml
  handlers:
    - include: handlers/packages_Debian.yml
      when: ansible_os_family == 'Debian'
    - include: handlers/packages_RedHat.yml
      when: ansible_os_family == 'RedHat'