---
# install packages
- include: ../../../common_tasks/packages/install.yml
  vars:
    packages: '{{hiera_eyaml_dependencies}}'
  tags:
    - hiera-eyaml
    - hiera-eyaml-packages

- name: install gems
  become: true
  command: "{{puppet_binpath}}/gem install {{item}} -- --use-system-libraries"
  with_items:
    - hiera-eyaml
    - hiera-eyaml-gpg
    - gpgme
  tags:
    - hiera-eyaml
    - hiera-eyaml-packages

- name: add symlink for hiera-eyaml
  become: true
  file:
    src: "{{puppet_binpath}}/eyaml"
    dest: "{{puppetlab_binpath}}/eyaml"
    state: link
  tags:
    - hiera-eyaml
    - hiera-eyaml-packages