---
- name: Clone Puppet task repo
  git: >
    repo={{puppet_task_repo}} dest={{puppet_task_dir}} accept_hostkey=true
  tags:
    - puppet-task

- name: Update Puppet modules
  command: librarian-puppet install
  args:
    chdir: "{{puppet_task_dir}}"
  tags:
    - puppet-task

- name: Blackbox post deploy
  command: /opt/blackbox/blackbox_postdeploy
  args:
    chdir: "{{puppet_task_dir}}"
  tags:
    - puppet-task

- name: Prepare Puppet Task directory
  become: true
  file:
    state: directory
    dest: "{{puppet_task_dir}}/var/{{item}}"
  with_items:
    - run
    - lib
    - log
  tags:
    - puppet-task

- name: Run Puppet Apply
  become: true
  command: >
    puppet apply --confdir=. {{puppet_apply_args}}
  args:
    chdir: "{{puppet_task_dir}}"
  tags:
    - puppet-task
