---
- name: Clone Puppet task repo
  git: >
    repo={{puppet_task_repo}} dest={{puppet_task_dir}} accept_hostkey=true
  tags:
    - puppet-task

- name: Update Puppet modules
  command: >
    {{puppetlab_binpath}}/librarian-puppet update
  args:
    chdir: "{{puppet_task_dir}}/code"
  environment:
    PATH: "{{puppetlab_binpath}}"
  tags:
    - puppet-task

- name: Blackbox post deploy
  command: /opt/blackbox/blackbox_postdeploy
  args:
    chdir: "{{puppet_task_dir}}"
  tags:
    - puppet-task

- name: Prepare Puppet Task directory
  become: true
  file:
    state: directory
    dest: "{{puppet_task_dir}}/var/run"
  tags:
    - puppet-task

- name: Run Puppet Apply
  become: true
  command: >
    /opt/puppetlabs/bin/puppet apply --confdir=.
    {{puppet_apply_args}}
  args:
    chdir: "{{puppet_task_dir}}"
  tags:
    - puppet-task