---
- name: Clone Puppet config repo
  git: >
    repo=git@github.com:stieizc/puppet-tasks.git depth=1
    dest=~/puppet-tasks accept_hostkey=true
  tags:
    - puppet-tasks

- name: Update Puppet modules
  command: /opt/puppetlabs/bin/librarian-puppet update
  args:
    chdir: ~/puppet-tasks/code
  tags:
    - puppet-tasks

- name: Blackbox post deploy
  command: /opt/blackbox/blackbox_postdeploy
  args:
    chdir: ~/puppet-tasks
  tags:
    - puppet-tasks

- name: Run Puppet Apply
  become: true
  command: >
    /opt/puppetlabs/bin/puppet apply --confdir=.
    --certname={{puppet_certname}} --environment={{puppet_environment}}
    code/environments/{{puppet_environment}}/manifests
  args:
    chdir: ~/puppet-tasks
  tags:
    - puppet-tasks