---
- include: ../../../common_tasks/packages/exists.yml
  vars:
    package: puppetlabs-release-pc1

- include: ../../../common_tasks/repo/enable_by_package.yml
  vars:
    repository_package_url: '{{puppet_repository_package_url}}'
  when: pkg_exists.changed and pkg_exists.rc