---
- include: repo_Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - puppet
    - puppet-repo

- include: repo_RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - puppet
    - puppet-repo