---
- include: ../../../common_tasks/packages/exists.yml
  vars:
    package: puppetlabs-release-pc1

- include: ../../../common_tasks/repo/enable_by_package.yml
  vars:
    repository_package_url: '{{puppet_repository_package_url}}'
    repository_package_file: '{{puppet_repository_package_file}}'
  when: pkg_exists.skipped and ansible_distribution_release != 'NA'

- include: ../../../common_tasks/repo/enable_by_package.yml
  vars:
    repository_package_url: '{{puppet_repository_package_latest_url}}'
    repository_package_file: '{{puppet_repository_package_file}}'
  when: pkg_exists.skipped and ansible_distribution_release == 'NA'